change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&@`' # Disables mentions and codeblocks
template: |
  ## Changes

  $CHANGES

# Automatically bump the version in this fashion by adding these labels to your PR.
version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
  # By default, bump the patch version
  default: patch
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

# These labels are enforced with the require-labels workflow
exclude-labels:
  - Internal
  - Trivial
categories:
  - title: Features
    labels:
      - Feature
  - title: Fixes
    labels:
      - Fix
