name: Releaser
run-name: Create a release of ${{ github.ref }} by @${{ github.actor }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - release
  workflow_dispatch:
    inputs:
      version:
        description: Override release version
      header:
        description: Markdown string to add before the template body
      name:
        description: Override name tag
      tag:
        description: Override release tag
      publish:
        description: Publish?
        type: boolean
        default: true


permissions:
  contents: read

jobs:
  release:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          name: ${{ inputs.name }}
          tag: ${{ inputs.tag }}
          header: ${{ inputs.header }}
          version: ${{ inputs.version }}
          # Automatically publish releases created on push
          publish: ${{ github.event_name == 'push' || inputs.publish }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
