name: Pull Request Labels
on:
    pull_request:
        types: [opened, labeled, unlabeled, synchronize, ready_for_review]
        branches: [main, release]

jobs:
    label:
        runs-on: ubuntu-latest
        if: github.event.pull_request.draft == false
        steps:
            - uses: mheap/github-action-required-labels@v3
              with:
                  mode: exactly
                  count: 1
                  labels: "Fix, Feature, Internal, Trivial"
                  add_comment: true
                  message: "This PR is being prevented from merging because you are missing one of the required labels: {{ provided }}."
